[package]
name = "gnostr-command"
version = "0.0.0"
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
git2        = "0.9.1"
argparse    = "0.2.2"
time = "0.1.42"
chrono = "0"
sha2 = "0.10.7"
pad = "0.1.6"
io = "0.0.2"
use = "0.0.0"
#crypto      = "0.4.0"
