[package]
name = "gnostr-command"
version = "0.0.8"
license = "MIT OR Apache-2.0"
description = "gnostr-command"
authors = [
  "Franz Heinzmann (Frando) <frando@unbiskant.org>",
  "Timo Tiuraniemi <timo.tiuraniemi@iki.fi>",
  "gnostr <gnostr>"
]
documentation = "https://docs.rs/hypercore-protocol"
homepage = "https://github.com/gnostr-org/gnostr-command"
repository = "https://github.com/gnostr-org/gnostr-command"
readme = "README.md"
edition = "2021"
keywords = ["dat", "p2p", "replication", "hypercore", "protocol", "gnostr","nostr", "git"]
categories = [
  "asynchronous",
  "concurrency",
  "cryptography",
  "data-structures",
  "encoding",
  "commanod-line",
  "git"
]

[lib]
# benchmarks are using criterion
bench = false

## [profile.release]
## debug = true

[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
async-channel = "1"
snow = { version = "0.9", features = ["risky-raw-split"] }
bytes = "1"
rand = "0.8"
blake2 = "0.10"
hex = "0.4"
async-trait = "0.1"
tracing = "0.1"
pretty-hash = "0.4"
futures-timer = "3"
futures-lite = "1"
hypercore = { version = "0.12", default-features = false, features = ["async-std", "cache", "js_interop_tests", "moka", "sparse"] }
sha2 = "0.10"
curve25519-dalek = "4"
crypto_secretstream = "0.2"
rust-crypto = "0.2.36"
git2        = "0.9.1"
argparse = "0.2.2"
time = "0.1.42"
chrono = "0"
nostr = "0.24.0"
nostr-sdk = "0.24.0"
wasi = { version = "0.10.0", features = ["std"] }
oorandom = "11.1.3"

##$ cargo add random-access-disk
##    Updating crates.io index
##      Adding random-access-disk v3.0.0 to dependencies.
##             Features:
##             + async-std
##             + libc
##             + sparse
##             - tokio
## NOTE:We favor async-std in this build config

random-access-storage = "5.0.0"
random-access-disk = { version = "3.0.0", default-features = false }
random-access-memory = "3.0.0"
tempfile = "3.8.1"

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes", "unstable"] }
async-compat = "0.2.1"
tokio = { version = "1.27.0", features = ["macros", "net", "process", "rt", "rt-multi-thread", "sync", "time"] }
env_logger = "0.7.1"
anyhow = "1.0.28"
instant = "0.1"
criterion = { version = "0.4", features = ["async_std"] }
pretty-bytes = "0.2.2"
duplexify = "1.1.0"
sluice = "0.5.4"
futures = "0.3.13"
log = "0.4"
test-log = { version = "0.2.11", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "fmt"] }

[features]
default = ["async-std", "sparse"]
wasm-bindgen = [
  "futures-timer/wasm-bindgen"
]
sparse = ["hypercore/sparse"]
cache = ["hypercore/cache"]
tokio = ["hypercore/tokio", "random-access-disk/tokio"]
async-std = ["hypercore/async-std", "random-access-disk/async-std"]
# Used only in interoperability tests under tests/js-interop which use the javascript version of hypercore
# to verify that this crate works. To run them, use:
# cargo test --features js_interop_tests
js_interop_tests = []
# debug = true

[[bench]]
name = "throughput"
harness = false

[[bench]]
name = "pipe"
harness = false
